name: mlp3
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - ffmpeg=4.3.2
  - freetype=2.11.0
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - icu=58.2
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lame=3.100
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.11
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.8
  - pytorch=1.10.2
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.8
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchvision=0.11.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - x264=1!161.3030
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - bokeh==2.4.2
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.0.0
    - colorcet==3.0.0
    - cycler==0.11.0
    - dask==2022.5.0
    - datashader==0.14.0
    - datashape==0.5.2
    - distributed==2022.5.0
    - fonttools==4.33.3
    - fsspec==2022.3.0
    - heapdict==1.0.1
    - holoviews==1.14.9
    - idna==3.3
    - imageio==2.19.2
    - importlib-metadata==4.11.3
    - kiwisolver==1.4.2
    - llvmlite==0.38.0
    - locket==1.0.0
    - markdown==3.3.7
    - matplotlib==3.5.2
    - msgpack==1.0.3
    - multipledispatch==0.6.0
    - networkx==2.8
    - numba==0.55.1
    - panel==0.13.0
    - param==1.12.1
    - partd==1.2.0
    - psutil==5.9.0
    - pyct==0.4.8
    - pynndescent==0.5.7
    - pyviz-comms==2.2.0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - requests==2.27.1
    - scikit-image==0.19.2
    - seaborn==0.11.2
    - shap==0.40.0
    - slicer==0.0.7
    - sortedcontainers==2.4.0
    - tblib==1.7.0
    - tifffile==2022.5.4
    - toolz==0.11.2
    - umap-learn==0.5.3
    - urllib3==1.26.9
    - xarray==2022.3.0
    - zict==2.2.0
