name: interpretability_project
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - tqdm
  - pytorch
  - torchvision=0.11
